# Generated by Django 5.0 on 2024-08-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='day',
        ),
    ]
