# Generated by Django 5.0 on 2024-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATM',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Super User')], default=1),
        ),
    ]
