# Generated by Django 5.0 on 2024-08-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_delete_atm_alter_customer_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
