# Generated by Django 5.0 on 2024-08-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_client', 'Can manage client')]},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_type',
        ),
    ]
