# Generated by Django 5.0 on 2024-08-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0010_alter_officeuser_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
