# Generated by Django 5.0 on 2024-08-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0012_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.account')),
            ],
        ),
    ]
