# Generated by Django 5.0 on 2024-08-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0013_transactionlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
