# Generated by Django 5.0 on 2024-08-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0014_delete_transactionlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionLogs',
            new_name='TransactionLog',
        ),
    ]
